# Change the prefix key to `C-t`.
set -g prefix C-t
unbind C-b
bind C-t send-prefix

bind c new-window -c "#{pane_current_path}"
# Emacs style keybindings.
bind C-2 split-window -h -c "#{pane_current_path}"
bind C-3 split-window -v -c "#{pane_current_path}"

# Clear the right status, I already have enough info in prompt.
set -g status-right ""
set -g status-bg red
set -g window-status-current-style "underscore"

# Enable RGB color if running in XTerm.
set-option -sa terminal-features ",xterm*:RGB"
# Enable 256 true color support.
set -g default-terminal "tmux-256color"
# Required for binding `C-2`/`C-3`.
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'

set -g bell-action none
# Turn the mouse on.
set -g mouse on
# The default scrolling history size is too small.
set -g history-limit 10000
# 1 is easier to type than 0 on keyboard.
set -g base-index 1
setw -g pane-base-index 1
# By default if you have Window 1, 2, 3 and delete Window 2, you then have
# Window 1, 3, this is not so useful for me, so always reassign numbers.
set-option -g renumber-windows on
